UPLOADED = "UPLOADED"
PROCESSING = "PROCESSING"
COMPLIANT = "COMPLIANT"
NON_COMPLIANT = "NON_COMPLIANT"
FAILED = "FAILED"

DOCUMENT_STATUSES = {
    UPLOADED,
    PROCESSING,
    COMPLIANT,
    NON_COMPLIANT,
    FAILED,
}

FINAL_DOCUMENT_STATUSES = {
    COMPLIANT,
    NON_COMPLIANT,
    FAILED,
}
